DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    EMP_ID TEXT,
    NAME TEXT,
    DEPT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
);

INSERT INTO DEPARTMENT (EMP_ID, NAME, DEPT_ID, MANAGER_ID, SALARY) VALUES
('E001', 'Alice Johnson', 'D001', 'M001', 75000),
('E002', 'Bob Smith', 'D002', 'M002', 62000),
('E003', 'Charlie Brown', 'D001', 'M001', 58000),
('E004', 'Diana Prince', 'D003', 'M003', 82000),
('E005', 'Ethan Hunt', 'D002', 'M002', 54000);

SELECT DEPT_ID AS "Department Code",
    Count(*) AS "NO of EMP"
FROM DEPARTMENT
GROUP BY DEPT_ID;

SELECT DEPT_ID, SUM(SALARY)
FROM DEPARTMENT
GROUP BY DEPT_ID;

SELECT DEPT_ID AS "Department Code",
    COUNT(*) AS "NO of EMP",
    SUM(SALARY) AS "TOTAL Salary"
FROM DEPARTMENT
GROUP BY DEPT_ID;

SELECT DEPT_ID AS "Department Code",
    SUM(SALARY) AS "TOTAL Salary"
FROM DEPARTMENT
WHERE MANAGER_ID = 'M002'
GROUP BY DEPT_ID;

SELECT DEPT_ID, COUNT(*) AS "NO of EMP",
FROM DEPARTMENT
GROUP BY DEPT_ID
HAVING COUNT(*) > 2;
