CREATE TABLE IF NOT EXISTS NOBLE_WIN (
    YEAR INT ,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBLE_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1970,'PHYSICS','Hannes Alfven','Sweden','SCIENTIST'),
(1971,'PHYSICS','Gerhard Herzberg','Canada','SCIENTIST'),
(1973,'PHYSICS','Heinrich Böll','Germany','SCIENTIST'),
(1974,'CHEMISTRY','Henry Kissinger','USA','LINGUIST'),
(1972,'LITERATURE','Friedrich Hayek','UK','ECONOMIST'),
(1975,'ECONOMICS','David Baltimore','USA','ECONOMIST'),
(1976,'BIOLOGY','David Baltimore','USA','PRIME MINISTER'),
(1987,'BIOLOGY','JOSEFH','USA','PRESIDENT'),
(1988,'CHEMISTRY','MARTIN','USA','SCIENTIST'),
(1989,'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1980,'PHYSICS','PETER','CHILE','SCIENTIST');

SELECT * FROM NOBLE_WIN 
WHERE SUBJECT NOT LIKE 'P%';