DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID INTEGER PRIMARY KEY,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT, 
    PRICE_REAL TEXT
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE_REAL) VALUES
('1', 'Chai', '1', '1', '10 boxes*20 bags', '18.00'),
('2', 'Chang', '1', '1', '24 - 12 oz bottles', '19.00'),
('3', 'Aniseed Syrup', '1', '2', '12 - 550 ml bottles', '10.00'),
('4', 'Chef Anton''s  Seasoning', '2', '2', '48 - 6 oz jars', '22.00'),
('5', 'Chef Anton''s  Mix', '2', '2', '36 boxes', '21.35');

SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT AVG(PRICE_REAL) AS AVERAGE_PRICE_REAL
FROM PRODUCTS;

SELECT SUM(PRICE_REAL) AS TOTAL_PRICE_REAL
FROM PRODUCTS;